<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'sign up Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'christy1392@hotmail.com',
		'to' => 'christy1392@hotmail.com'
	),
	'fields' => array(
		'custom_U1610' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 3,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U1601' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'School Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'School Name\' is required.'
			)
		),
		'custom_U1593' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'School Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'School Address\' is required.'
			)
		),
		'custom_U1597' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'City',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'City\' is required.'
			)
		),
		'custom_U1588' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'State',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'State\' is required.'
			)
		),
		'custom_U1619' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Zip code',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Zip code\' is required.'
			)
		),
		'custom_U1605' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Country',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Country\' is required.'
			)
		),
		'custom_U1710' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Work Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Work Phone\' is required.'
			)
		),
		'custom_U1722' => array(
			'order' => 10,
			'type' => 'checkbox',
			'label' => 'Read Terms of Service',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Read Terms of Service\' is required.'
			)
		),
		'custom_U1779' => array(
			'order' => 11,
			'type' => 'checkbox',
			'label' => 'Read Privacy Policy',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Read Privacy Policy\' is required.'
			)
		),
		'custom_U1791' => array(
			'order' => 12,
			'type' => 'radiogroup',
			'label' => 'Select Gender',
			'required' => true,
			'optionItems' => array(
				'Male',
				'Female'
			),
			'errors' => array(
				'required' => 'Field \'Select Gender\' is required.',
				'format' => 'Field \'Select Gender\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
